### ISSUE TITLE
Problems with the 'Home' page

### ISSUE THREAD

**Issue by TheOverlord95** [Warzone2100/wz2100-autohost.net#3]
1. The english is, in general, lacking grammar. I have posted some fixes in the #autohost discord chat in the main WZ discord channel.
2. There should be some info about registered linked accounts.
3. It should mention something about about vpns being not allowed to join.
4. The graph breaks when you use the mouse wheel while hovering over it with your cursor.
5. I'm not sure what maxsupermanhd meant by this but it should say something about how "we don't chase profiles."

**Comment by maxsupermanhd** [comment]
Unable to reproduce

**Comment by TheOverlord95** [comment]
Covertly fixed = "Unable to reproduce"
